name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check disk space (before)
      run: df -h
      
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Build in Release Mode
      run: cargo build --release --verbose

    - name: Check disk space (after build)
      run: df -h
      
    - name: Clean up build artifacts
      run: rm -rf target/

    - name: Run tests
      run: cargo test --release --verbose
